#!/bin/sh

ADDR=$(jupyter notebook list | grep http | awk '{print $1}')
if ! [ "$ADDR" ]; then
    IP=$(ip addr | grep eth0 | grep inet | awk '{print $2}' | cut -d/ -f1)
    # by default job control doesn't work in scripts
    set -m
    jupyter notebook --no-browser --ip $IP --port 8888 &
    sleep 1
    ADDR=$(jupyter notebook list | grep http | awk '{print $1}')
fi

/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe "$ADDR"

# without fg it is not possible to shutdown the server with Ctrl-C
fg %1 2>/dev/null || exit 0 # for several jsarts with the running server

### MISC NOTES
# To generate config
# jupyter notebook --generate-config

# To stop blink - create ~/.jupyter/nbconfig/edit.json
#{
#  "Editor": {
#    "codemirror_options": {
#      "vimMode": true,
#      "keyMap": "vim",
##      "autoCloseBrackets": false,
#      "cursorBlinkRate": 0
#    }
#  }
#}

# To text editing - pip install jupytext

